- pipeline: "Test version 1.16-1.17"
  on: "EVENT"
  events:
  - type: "PUSH"
    refs:
    - "refs/heads/master"
    - "refs/heads/Objetivo-6"
  priority: "NORMAL"
  fail_on_prepare_env_warning: true
  actions:
  - action: "test-action-1.16"
    type: "BUILD"
    working_directory: "/src/github.com/Xileon310/GoParty"
    docker_image_name: "library/golang"
    docker_image_tag: "1.16.13"
    execute_commands:
    - "export GOPATH=/"
    - "export GO15VENDOREXPERIMENT=1"
    - "go test -v ./..."
    volume_mappings:
    - "/:/src/github.com/Xileon310/GoParty"
    cache_base_image: true
    shell: "BASH"
  - action: "test-action-1.17"
    type: "BUILD"
    working_directory: "/src/github.com/Xileon310/GoParty"
    docker_image_name: "library/golang"
    docker_image_tag: "1.17.6"
    execute_commands:
    - "export GOPATH=/"
    - "export GO15VENDOREXPERIMENT=1"
    - "go test -v ./..."
    volume_mappings:
    - "/:/src/github.com/Xileon310/GoParty"
    cache_base_image: true
    shell: "BASH"
