version: 2.1

on: [push, pull_request]

jobs:
  test-app-github-action:
    runs-on: xileon/goparty:latest
    name: "Test docker image"
    steps:
      - run:
          name: "Test app"
          command: "task test"

workflows:
  test-app-workflow-github-action:
    jobs:
      - test-app-github-action
