on: pull_request

jobs:
  run-tests:
    name: Run tests Go ${{ matrix.golang }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.13

      - name: Run tests
        run: go test -v ./...
