version: 2.1

jobs:
  test-app-ci:
    docker:
      - image: xileon/goparty:latest
    steps:
      - checkout
      - run:
          name: "Test app"
          command: "task test"

workflows:
  test-app-workflow:
    jobs:
      - test-app-ci
