name: Project Tests

on: push

jobs:
  run-tests:
    strategy:
      matrix:
        golang: ['1.16', '1.17']
    name: Run tests Go ${{ matrix.golang }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.golang }}

      - name: Run tests
        run: go test -v ./...
          