on: [push, pull_request]

jobs:
  test-app-github-action:
    runs-on: xileon/goparty:latest
    name: "Test docker image"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Test app
        uses: addnab/docker-run-action@v3
        with:
          image: xileon/goparty:latest
          run: task test
